### ISSUE TITLE
Using invalid xAPI interaction type

### ISSUE THREAD

**Issue by otacke** [h5p/h5p-goals-assessment-page#22]
The value '_compound_' used in https://github.com/h5p/h5p-goals-assessment-page/blob/005aaffcf59a5fff411ae1e22ccf03ccc28849ea/goals-assessment-page.js#L348 is not among the allowed values for interaction types, cmp. https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#interaction-types The xAPI validator at https://lrs.adlnet.gov/statementvalidator declares xAPI statements using that value as invalid. While this may be fine for H5P itself, it may cause trouble in a LRS or other systems evaluating the xAPI statements.

The value seems to be relevant for the H5P report module though, see: https://github.com/h5p/h5p-php-report/issues/11

**Comment by fnoks** [comment]
Fixed: https://github.com/h5p/h5p-goals-assessment-page/commit/477b4b7f03d322ee03dc8e7b8f676526ba03cafe
