### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by tmkarlsen** [h5p/h5p-goals-assessment-page#27]
"Possible ratings", "Goals" and "Rating" is missing within the language files and cannot be translated in any way as far as I can see.

**Comment by tmkarlsen** [comment]
@fnoks Do you know if this will be something that can be added?

**Comment by fnoks** [comment]
@tmkarlsen: It is really strange no one has noticed this previously. Thanks for letting us know. I have added it to my TODO-list :+1:

**Comment by fnoks** [comment]
This is fixed here: https://github.com/h5p/h5p-goals-assessment-page/commit/760efe7dcd632cebf493af62cae72f20c0bc7eed
